(()=>{
const SUPABASE_URL='https://pdhrifgwjuuafhajypiw.supabase.co';
const SUPABASE_KEY='sb_publishable_SnIw4x0bG7m0dCENqOkXfg_YvjX4JrU';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,profile=null,saveTimer=null,currentLeague=null;
const accountButton=document.querySelector('#accountButton'),shell=document.querySelector('.shell');
const menu=document.createElement('div');menu.className='accountMenu';menu.hidden=true;document.body.append(menu);
const leagueView=document.createElement('section');leagueView.className='leagueView';leagueView.hidden=true;document.body.append(leagueView);
const friendDialog=document.createElement('dialog');friendDialog.className='friendDialog';friendDialog.innerHTML='<div class="friendHead"><h2>League member</h2><button class="friendClose">Close</button></div><div class="friendBody"></div>';document.body.append(friendDialog);friendDialog.querySelector('.friendClose').onclick=()=>friendDialog.close();
function notice(text,error=false){const n=document.createElement('div');n.className='authNotice'+(error?' error':'');n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),2600)}
async function signIn(){const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)notice(error.message,true)}
async function signOut(){await sb.auth.signOut();session=null;profile=null;sessionStorage.removeItem('cp-cloud-loaded');location.reload()}
accountButton.onclick=()=>{if(!session)return signIn();renderMenu();menu.hidden=false};menu.onclick=e=>{if(e.target===menu)menu.hidden=true};
function renderMenu(){const name=profile?.username?'@'+profile.username:(session.user.user_metadata?.full_name||session.user.email);menu.innerHTML=`<div class="accountMenuCard"><h3>${esc(name)}</h3><p><span class="cloudBadge">● Saved to cloud</span><br>${esc(session.user.email||'')}</p><button class="menuAction" data-open-leagues>My leagues</button><button class="menuAction" data-backup>Download data backup</button><button class="menuAction danger" data-signout>Sign out</button></div>`;menu.querySelector('[data-open-leagues]').onclick=()=>{menu.hidden=true;showLeagues()};menu.querySelector('[data-backup]').onclick=downloadBackup;menu.querySelector('[data-signout]').onclick=signOut}
function downloadBackup(){const blob=new Blob([JSON.stringify(window.store,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cp-nfl-hub-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.queueCloudSave=()=>{if(!session)return;clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{const {error}=await sb.from('user_state').upsert({user_id:session.user.id,state:window.store,updated_at:new Date().toISOString()});if(error)notice('Cloud save failed — local copy is safe',true)},700)};
async function bootstrap(s){session=s;if(!s){accountButton.textContent='Sign in with Google';return}const {data:p}=await sb.from('profiles').select('*').eq('id',s.user.id).single();profile=p;accountButton.classList.add('signedIn');accountButton.innerHTML=`${p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:''}${esc(p?.username?'@'+p.username:(s.user.user_metadata?.given_name||'Account'))}`;if(!p?.username)await chooseUsername();const marker=sessionStorage.getItem('cp-cloud-loaded'),{data:cloud}=await sb.from('user_state').select('state,updated_at').eq('user_id',s.user.id).maybeSingle();if(!cloud){await sb.from('user_state').upsert({user_id:s.user.id,state:window.store,updated_at:new Date().toISOString()});notice('Your saved rankings and picks are now in your account')}else if(marker!==s.user.id){localStorage.setItem('carson-power-rankings',JSON.stringify(cloud.state));sessionStorage.setItem('cp-cloud-loaded',s.user.id);location.reload()}else sessionStorage.setItem('cp-cloud-loaded',s.user.id)}
async function chooseUsername(){let username='';while(!username){const value=prompt('Choose a username for your leagues (3–24 letters, numbers, or underscores):','');if(value===null){notice('Choose a username from Account when you are ready',true);return}if(!/^[A-Za-z0-9_]{3,24}$/.test(value)){alert('Use 3–24 letters, numbers, or underscores.');continue}const {data,error}=await sb.from('profiles').update({username:value,updated_at:new Date().toISOString()}).eq('id',session.user.id).select().single();if(error){alert(error.code==='23505'?'That username is taken. Try another.':error.message)}else{profile=data;username=value}}}
async function showLeagues(){if(!session){await signIn();return}shell.hidden=true;document.querySelector('.productNav')?.setAttribute('hidden','');document.querySelector('.pickemView')?.setAttribute('hidden','');leagueView.hidden=false;await renderLeagues()}
async function renderLeagues(){leagueView.innerHTML='<div class="emptyLeague">Loading your leagues…</div>';const {data:memberships,error}=await sb.from('league_members').select('league_id,role,leagues(id,name,join_code,owner_id)').eq('user_id',session.user.id);if(error){leagueView.innerHTML='<div class="emptyLeague">Leagues are temporarily unavailable.</div>';return}const leagues=(memberships||[]).map(x=>({...x.leagues,role:x.role}));if(currentLeague&&!leagues.some(x=>x.id===currentLeague))currentLeague=null;if(!currentLeague&&leagues[0])currentLeague=leagues[0].id;leagueView.innerHTML=`<div class="leagueHero"><div><div class="eyebrow">Friends & competition</div><h1>Your leagues</h1><p>Share a code, compare picks, and see everybody’s weekly rankings.</p></div><div class="leagueActions"><button class="btn" data-back>← Back to rankings</button></div></div><div class="leagueGrid"><aside class="leaguePanel"><h3>Leagues</h3><div class="leagueList">${leagues.length?leagues.map(l=>`<button class="leagueItem ${l.id===currentLeague?'active':''}" data-league="${l.id}"><div><b>${esc(l.name)}</b><span>${l.role==='owner'?'Owner':'Member'}</span></div></button>`).join(''):'<div class="emptyLeague">No leagues yet.</div>'}</div><h3 style="margin-top:20px">Create one</h3><form class="leagueForm" data-create><input name="name" maxlength="48" placeholder="League name" required><button>Create</button></form><h3 style="margin-top:20px">Join one</h3><form class="leagueForm" data-join><input name="code" maxlength="8" placeholder="8-character code" required><button>Join</button></form></aside><main class="leaguePanel" id="leagueMain"></main></div>`;leagueView.querySelector('[data-back]').onclick=backToApp;leagueView.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{currentLeague=b.dataset.league;renderLeagues()});leagueView.querySelector('[data-create]').onsubmit=createLeague;leagueView.querySelector('[data-join]').onsubmit=joinLeague;await renderLeagueMain(leagues.find(x=>x.id===currentLeague))}
function backToApp(){leagueView.hidden=true;shell.hidden=false;document.querySelector('.productNav')?.removeAttribute('hidden')}
async function createLeague(e){e.preventDefault();const name=new FormData(e.target).get('name');const {data,error}=await sb.rpc('create_league',{league_name:name});if(error)return notice(error.message,true);currentLeague=data?.[0]?.id;notice('League created');renderLeagues()}
async function joinLeague(e){e.preventDefault();const code=new FormData(e.target).get('code');const {data,error}=await sb.rpc('join_league',{code});if(error)return notice(error.message,true);currentLeague=data?.[0]?.id;notice('League joined');renderLeagues()}
async function renderLeagueMain(league){const main=leagueView.querySelector('#leagueMain');if(!league){main.innerHTML='<div class="emptyLeague"><b>Create or join a league</b><br>Once your friends join, you can open their rankings and Pick’em stats here.</div>';return}main.innerHTML=`<h2>${esc(league.name)}</h2><p class="standLabel">Invite code</p><button class="joinCode" data-copy>${esc(league.join_code)} <span>⧉</span></button><h3 style="margin-top:24px">Members</h3><div class="leagueList" id="memberList"><div class="emptyLeague">Loading members…</div></div>`;main.querySelector('[data-copy]').onclick=async()=>{await navigator.clipboard.writeText(league.join_code);notice('Join code copied')};const {data:members}=await sb.from('league_members').select('user_id,role,joined_at').eq('league_id',league.id).order('joined_at');const ids=(members||[]).map(m=>m.user_id);const {data:profiles}=ids.length?await sb.from('profiles').select('id,username,display_name,avatar_url').in('id',ids):{data:[]};const map=Object.fromEntries((profiles||[]).map(p=>[p.id,p]));main.querySelector('#memberList').innerHTML=(members||[]).map(m=>{const p=map[m.user_id]||{};return `<button class="memberItem" data-user="${m.user_id}">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:'<span class="memberAvatar">🏈</span>'}<div><b>${esc(p.username?'@'+p.username:(p.display_name||'Member'))}</b><span>${m.role==='owner'?'League owner':'Member'}</span></div><div class="memberStats">View<br>profile →</div></button>`}).join('')||'<div class="emptyLeague">No members yet.</div>';main.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>openFriend(b.dataset.user,map[b.dataset.user]))}
async function openFriend(userId,p){const {data,error}=await sb.from('user_state').select('state').eq('user_id',userId).maybeSingle();if(error||!data)return notice('That member has not saved any data yet',true);const s=data.state||{},week=+(s.week||1),rank=(s.weeks||{})[week]||[],games=Object.values(s.pickem?.games||{}),picks=s.pickem?.picks||{},graded=games.filter(g=>g.completed&&g.winner&&picks[g.id]),correct=graded.filter(g=>picks[g.id]===g.winner).length;friendDialog.querySelector('h2').textContent=p?.username?'@'+p.username:(p?.display_name||'League member');friendDialog.querySelector('.friendBody').innerHTML=`<div class="friendPickStats"><div class="friendStat"><b>${Object.keys(picks).length}</b><span>Picks made</span></div><div class="friendStat"><b>${graded.length}</b><span>Graded</span></div><div class="friendStat"><b>${graded.length?Math.round(correct/graded.length*100):0}%</b><span>Accuracy</span></div></div><h3>Week ${week} power rankings</h3><div class="friendRankGrid">${rank.map((c,i)=>`<div class="friendRank"><b>${i+1}</b><img src="${logo(c)}" alt=""><span>${esc(info[c]?.name||c)}</span></div>`).join('')}</div>`;friendDialog.showModal()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
sb.auth.getSession().then(({data})=>bootstrap(data.session));sb.auth.onAuthStateChange((_event,s)=>{if(s?.user?.id!==session?.user?.id)bootstrap(s)});
})();
