(()=>{const home=document.querySelector('#homeView'),nfl=document.querySelector('#nflView'),tabs=document.querySelectorAll('[data-global-view]'),feed=document.querySelector('#wireFeed'),live=document.querySelector('#wireLive'),input=document.querySelector('#callText');let type='Take',announcements=[],channel=null;
const account=()=>window.ledgeAccount||{},isOwner=()=>!!account().profile?.site_owner;
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===b));const isHome=b.dataset.globalView==='home';home.hidden=!isHome;nfl.hidden=isHome;if(isHome){renderFeed();loadAnnouncements()}});
function bindTypes(){document.querySelectorAll('[data-call-type]').forEach(b=>b.onclick=()=>{type=b.dataset.callType;document.querySelectorAll('[data-call-type]').forEach(x=>x.classList.toggle('active',x===b))})}bindTypes();
function activateAccount(){const slot=document.querySelector('#ownerCallType');if(isOwner()&&!slot.querySelector('[data-call-type="Announcement"]')){slot.innerHTML='<button class="callType" data-call-type="Announcement">✦ Announcement</button>';bindTypes()}loadAnnouncements();renderFeed()}
window.addEventListener('ledge-account-ready',activateAccount);if(window.ledgeAccount)activateAccount();
document.querySelector('#postCall').onclick=async()=>{const text=input.value.trim();if(!text)return window.toast?.('Write your call first');if(type==='Announcement'){if(!isOwner())return window.toast?.('Owner access required');const {error}=await account().sb.from('announcements').insert({author_id:account().session.user.id,body:text});if(error)return window.toast?.(error.message);input.value='';await loadAnnouncements();window.toast?.('Announcement broadcast to every account');return}if(!store.wirePosts)store.wirePosts=[];store.wirePosts.unshift({id:Date.now(),type,text,createdAt:new Date().toISOString()});input.value='';save();renderFeed();window.toast?.(type==='Hot Take'?'Hot take locked in':'Call posted to your profile')};
document.querySelector('#wireRefresh').onclick=()=>{loadLive();loadAnnouncements()};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ago(date){const mins=Math.max(0,Math.floor((Date.now()-new Date(date))/60000));return mins<1?'now':mins<60?mins+'m':mins<1440?Math.floor(mins/60)+'h':Math.floor(mins/1440)+'d'}
function bigUpsetReceipts(){const games=Object.values(store.pickem?.games||{}),picks=store.pickem?.picks||{};return games.filter(g=>g.completed&&g.winner&&picks[g.id]===g.winner&&g.underdog===g.winner&&+(g.winner===g.home?g.homeML:g.awayML)>=200).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,2).map(g=>({receipt:true,correct:true,type:'UPSET RECEIPT',text:'Called the '+(info[g.winner]?.name||g.winner.toUpperCase())+' upset at '+(g.winner===g.home?'+'+g.homeML:'+'+g.awayML)+'.',createdAt:g.date}))}
async function loadAnnouncements(){if(!account().session||!account().sb)return;const {data}=await account().sb.from('announcements').select('id,body,created_at,author_id').order('created_at',{ascending:false}).limit(20);announcements=data||[];if(!channel){channel=account().sb.channel('ledge-announcements').on('postgres_changes',{event:'INSERT',schema:'public',table:'announcements'},payload=>{announcements.unshift(payload.new);renderFeed()}).subscribe()}renderFeed()}
function renderFeed(){const posts=[...(store.wirePosts||[]),...bigUpsetReceipts()].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),owner=isOwner(),avatar=owner?'assets/cp-logo.png?v=20260921-6':'',ann=announcements.map(a=>`<article class="wirePost announcementPost ownerPost"><div class="postHead"><div class="postAvatar" data-open-profile>${avatar?`<img src="${avatar}" style="width:100%;height:100%;object-fit:contain">`:'CP'}</div><div data-open-profile><div class="ownerIdentity">${avatar?`<img src="${avatar}">`:''}<span>@Carson · FOUNDING OWNER</span></div><div class="postMeta">${ago(a.created_at)} · Broadcast to Ledge</div></div><span class="postBadge">ANNOUNCEMENT</span></div><p>${esc(a.body)}</p><div class="postFooter"><span>♡ React</span><span>↗ Share</span><span>Official Ledge update</span></div></article>`).join(''),own=posts.map(p=>`<article class="wirePost ${p.receipt?(p.correct?'correctReceipt':'missedReceipt'):''} ${owner?'ownerPost':''} ${p.type==='Hot Take'?'hotTakePost':''}"><div class="postHead"><div class="postAvatar" data-open-profile>${avatar?`<img src="${avatar}" style="width:100%;height:100%;object-fit:contain">`:(p.receipt?'✓':'CP')}</div><div data-open-profile><div class="${owner?'ownerIdentity':'postWho'}">${owner&&avatar?`<img src="${avatar}">`:''}<span>@Carson${owner?' · FOUNDING OWNER':''}</span></div><div class="postMeta">${ago(p.createdAt)} · On the record</div></div><span class="postBadge">${esc(p.type)}</span></div><p>${esc(p.text)}</p><div class="postFooter"><span>♡ React</span><span>↗ Share</span><span>${p.type==='Hot Take'?'🔥 Revisit this take':p.receipt?'View receipt':'View profile'}</span></div></article>`).join('');
feed.innerHTML=ann+(own||'<div class="wireEmpty">Your calls and major upset receipts will appear here. Ordinary picks stay on your profile.</div>')+`<article class="wirePost sourcePost"><div class="postHead"><div class="postAvatar">L</div><div><div class="postWho">Ledge Wire</div><div class="postMeta">Source feed preview</div></div><span class="postBadge">BREAKING</span></div><p>Verified NFL news from trusted reporters will appear here alongside the calls it affects.</p><a class="sourceLink" href="https://x.com/AdamSchefter" target="_blank" rel="noopener">Open Adam Schefter on X ↗</a></article>`;feed.querySelectorAll('[data-open-profile]').forEach(x=>x.onclick=()=>window.openLedgeProfile?.())}
async function loadLive(){live.innerHTML='<div class="wireGame">Refreshing the NFL slate…</div>';try{const w=store.pickem?.week&&store.pickem.week<=18?store.pickem.week:2,r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?seasontype=2&week=${w}&dates=2026&limit=100&_=${Date.now()}`,{cache:'no-store'}),j=await r.json(),now=Date.now(),events=(j.events||[]).sort((a,b)=>{const sa=a.status?.type?.state,sb=b.status?.type?.state,pa=sa==='in'?0:sa==='pre'?1:2,pb=sb==='in'?0:sb==='pre'?1:2;if(pa!==pb)return pa-pb;return pa===2?new Date(b.date)-new Date(a.date):new Date(a.date)-new Date(b.date)}).slice(0,12);live.innerHTML=events.length?events.map(ev=>{const c=ev.competitions?.[0],teams=c?.competitors||[],h=teams.find(x=>x.homeAway==='home'),a=teams.find(x=>x.homeAway==='away'),state=ev.status?.type?.state,isLive=state==='in',kick=new Date(ev.date),time=state==='pre'?(kick.toDateString()===new Date(now).toDateString()?'Tonight · ':'')+kick.toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'}):ev.status?.type?.shortDetail||'';return `<article class="wireGame ${isLive?'live':''}"><div class="wireGameTop"><span>${esc(time||'NFL')}</span><span class="${isLive?'live':''}">${isLive?'● LIVE':state==='post'?'FINAL':'UPCOMING'}</span></div><div class="wireTeam"><img src="${a?.team?.logo||''}"><span>${esc(a?.team?.shortDisplayName||'Away')}</span><b>${state==='pre'?'':esc(a?.score||0)}</b></div><div class="wireTeam"><img src="${h?.team?.logo||''}"><span>${esc(h?.team?.shortDisplayName||'Home')}</span><b>${state==='pre'?'':esc(h?.score||0)}</b></div></article>`}).join(''):'<div class="wireGame">No games found for this week.</div>'}catch(e){live.innerHTML='<div class="wireGame">Live scores are temporarily unavailable.</div>'}}
renderFeed();loadLive()})();