(()=>{const home=document.querySelector('#homeView'),nfl=document.querySelector('#nflView'),tabs=document.querySelectorAll('[data-global-view]'),feed=document.querySelector('#wireFeed'),live=document.querySelector('#wireLive'),input=document.querySelector('#callText');let type='Take';
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===b));const isHome=b.dataset.globalView==='home';home.hidden=!isHome;nfl.hidden=isHome;if(isHome)renderFeed()});
document.querySelectorAll('[data-call-type]').forEach(b=>b.onclick=()=>{type=b.dataset.callType;document.querySelectorAll('[data-call-type]').forEach(x=>x.classList.toggle('active',x===b))});
document.querySelector('#postCall').onclick=()=>{const text=input.value.trim();if(!text)return window.toast?.('Write your call first');if(!store.wirePosts)store.wirePosts=[];store.wirePosts.unshift({id:Date.now(),type,text,createdAt:new Date().toISOString()});input.value='';save();renderFeed();window.toast?.('Call posted to The Wire')};
document.querySelector('#wireRefresh').onclick=loadLive;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ago(date){const mins=Math.max(0,Math.floor((Date.now()-new Date(date))/60000));return mins<1?'now':mins<60?mins+'m':mins<1440?Math.floor(mins/60)+'h':Math.floor(mins/1440)+'d'}
function receipts(){const games=Object.values(store.pickem?.games||{}),picks=store.pickem?.picks||{};return games.filter(g=>g.completed&&g.winner&&picks[g.id]).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,2).map(g=>({receipt:true,type:picks[g.id]===g.winner?'Correct call':'Missed call',text:(picks[g.id]===g.winner?'Called ':'Missed ')+(info[picks[g.id]]?.name||picks[g.id].toUpperCase())+' in '+(info[g.away]?.name||g.away.toUpperCase())+' at '+(info[g.home]?.name||g.home.toUpperCase())+'.',createdAt:g.date}))}
function renderFeed(){const posts=[...(store.wirePosts||[]),...receipts()].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const own=posts.map(p=>`<article class="wirePost ${p.receipt?'receiptPost':''}"><div class="postHead"><div class="postAvatar">${p.receipt?'✓':'CP'}</div><div><div class="postWho">@Carson</div><div class="postMeta">${ago(p.createdAt)} · On the record</div></div><span class="postBadge">${esc(p.type)}</span></div><p>${esc(p.text)}</p><div class="postFooter"><span>♡ React</span><span>↗ Share</span><span>View receipt</span></div></article>`).join('');
feed.innerHTML=(own||'<div class="wireEmpty">Your calls and graded pick receipts will appear here.</div>')+`<article class="wirePost sourcePost"><div class="postHead"><div class="postAvatar">L</div><div><div class="postWho">Ledge Wire</div><div class="postMeta">Source feed preview</div></div><span class="postBadge">BREAKING</span></div><p>Verified NFL news from trusted reporters will appear here alongside the picks and rankings it affects.</p><a class="sourceLink" href="https://x.com/AdamSchefter" target="_blank" rel="noopener">Open Adam Schefter on X ↗</a></article>`}
async function loadLive(){live.innerHTML='<div class="wireGame">Refreshing the NFL slate…</div>';try{const w=store.pickem?.week&&store.pickem.week<=18?store.pickem.week:2,r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?seasontype=2&week=${w}&dates=2026&limit=20&_=${Date.now()}`,{cache:'no-store'}),j=await r.json(),events=(j.events||[]).slice(0,8);live.innerHTML=events.length?events.map(ev=>{const c=ev.competitions?.[0],teams=c?.competitors||[],h=teams.find(x=>x.homeAway==='home'),a=teams.find(x=>x.homeAway==='away'),state=ev.status?.type?.state,isLive=state==='in';return `<article class="wireGame ${isLive?'live':''}"><div class="wireGameTop"><span>${esc(ev.status?.type?.shortDetail||'NFL')}</span><span class="${isLive?'live':''}">${isLive?'● LIVE':state==='post'?'FINAL':'UPCOMING'}</span></div><div class="wireTeam"><img src="${a?.team?.logo||''}"><span>${esc(a?.team?.shortDisplayName||'Away')}</span><b>${state==='pre'?'':esc(a?.score||0)}</b></div><div class="wireTeam"><img src="${h?.team?.logo||''}"><span>${esc(h?.team?.shortDisplayName||'Home')}</span><b>${state==='pre'?'':esc(h?.score||0)}</b></div></article>`}).join(''):'<div class="wireGame">No games found for this week.</div>'}catch(e){live.innerHTML='<div class="wireGame">Live scores are temporarily unavailable.</div>'}}
renderFeed();loadLive()})();